---
abstract: 'all modern features + unicode support in one pragma'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: uni-perl
no_index:
  directory:
    - t
    - inc
provides:
  uni::perl:
    file: lib/uni/perl.pm
    version: 0.91
requires:
  perl: v5.10.0
version: 0.91
